licenseKey: bb7a4dc5565cfa8d7771216bcebd99b8FFFFNRAL

k8sLog: { enabled: false }
k8sLogWindows: { enabled: false }
auditLog: { enabled: false }

fluentBit:
  logLevel: info
  useDefaultConfig: false

  config:
    service: |-
      [SERVICE]
          Flush 1
          Log_Level ${LOG_LEVEL}
          Daemon off
          Parsers_File /fluent-bit/custom/parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020

    inputs: |-
      [INPUT]
          Name   tail
          Path   /var/log/containers/*.log
          Exclude_Path /var/log/containers/newrelic-logging*_newrelic_*.log
          Tag    kube.*
          Parser cri

    filters: |-
      # 1) 파드/네임스페이스 메타데이터 부착 (grep에서 사용)
      [FILTER]
          Name            kubernetes
          Match           kube.*
          Kube_Tag_Prefix kube.var.log.containers.
          Merge_Log       Off

      # 2) CRI log 필드(JSON 문자열) 병합
      [FILTER]
          Name          parser
          Match         kube.*
          Key_Name      log
          Parser        json
          Reserve_Data  On
          Preserve_Key  Off

      # 3) 파드명이 newrelic-test-app* , auth-api*인 것만 통과
      [FILTER]
          Name   grep
          Match  kube.*
          Regex  $kubernetes['pod_name'] ^(newrelic-test-app|auth-api)

      # 4) 기본 키 마스킹
      [FILTER]
          Name       modify
          Match      kube.*
          Condition  Key_exists credit_card
          Set        credit_card REDACTED_CARD
      [FILTER]
          Name       modify
          Match      kube.*
          Condition  Key_exists authorization
          Set        authorization REDACTED_AUTH
      [FILTER]
          Name       modify
          Match      kube.*
          Condition  Key_exists password
          Set        password REDACTED_PW

      # 5) Lua 마스킹 (전화/이메일)
      [FILTER]
          Name    lua
          Match   kube.*
          script  /fluent-bit/scripts/phone_email_mask.lua
          call    mask_email_phone

    outputs: |-
      [OUTPUT]
          Name   stdout
          Match  kube.*
      [OUTPUT]
          Name         nrlogs
          Match        kube.*
          license_key  ${LICENSE_KEY}

extraVolumes:
 - name: custom-parsers
   configMap:
     name: custom-parsers


extraVolumeMounts:
 - name: custom-parsers
   mountPath: /fluent-bit/custom
   readOnly: true
