apiVersion: v1
kind: ConfigMap
metadata:
  name: newrelic-test-config
data:
  application.properties: |
    server.port=8080
    spring.application.name=newrelic-test-app
    logging.level.com.example.newrelictest=INFO
    logging.level.root=INFO
    logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
    management.endpoints.web.exposure.include=health,info,metrics
    management.endpoint.health.show-details=always